### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [rafathefull/harbour#1]
I would like to use your grammar for Harbour but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@rafathefull @QuimFerrer @manuelcalerosolis @angelsalom Did you get a chance to look into this? I'd like to use your grammar at [github/linguist](https://github.com/github/linguist) to highlight Harbour code on GitHub.

**Comment by pchaigno** [comment]
:flags: Flagging as stale (?)

**Comment by rafathefull** [comment]
Hi, licencies is GPL

**Comment by pchaigno** [comment]
@rafathefull Thanks for your answer.
Could you add a note in the README or a LICENSE file about that? It's required for [github/linguist](https://github.com/github/linguist) and I think the license needs to be distributed with the code anyway :-)
